name: mwc_example_workspace
repository: https://github.com/zoocityboy/melos_workspace_cleaner

packages:
  - "."
  - packages/**
ide:
  intellij: false
command:
  version:
    linkToCommits: true
    workspaceChangelog: true
  bootstrap:
    dev_dependencies:
      test: ^1.24.0
  clean:
    hooks:
      pre: mwc
scripts:
  ci:analyze:
    description: |
      Run `dart analyze` in all packages.
    exec: dart analyze --fatal-infos --fatal-warnings .
  ci:test:
    description: |
      Run `dart test` in all packages.
    exec: dart test
