name: melos_workspace
repository: https://github.com/zoocityboy/melos_workspace_cleaner
ide:
  intellij: false
packages:
  - "."
  - example/**
command:
  bootstrap:
    hooks:
      post: |
        melos run format
  version:
    workspaceChangelog: false
    branch: main
    message: |
      chore: cut package releases 🎉
scripts:
  postclean: >
    melos exec -c 1 -- \
      "flutter pub get"
  format:
    description: |
      Run `dart format` in all packages.
    run: |
      melos exec -c 1 -- \
        "dart format --set-exit-if-changed lib"
  pana:
    description: |
      Run `dart analyze` in all packages.
    run: |
      dart pub global activate pana
      pana -j > reports/pana.json
    packageFilters:
      scope: "mwc"
  ci:analyze:
    description: |
      Run `dart analyze` in all packages.
    run: |
      dart analyze --fatal-infos --fatal-warnings .
    packageFilters:
      scope: "mwc"
  ci:test:
    description: |
      Run `dart test` in all packages.
    run: |
      dart pub global activate coverage
      dart test --coverage=coverage --debug
      dart pub global run coverage:format_coverage \
      --lcov \
      --in=coverage \
      --out=coverage/lcov.info \
      --packages=.dart_tool/package_config.json \
      --report-on=lib
    packageFilters:
      scope: "mwc"
