name: melos_workspace
repository: https://github.com/zoocityboy/melos_workspace_cleaner
ide:
  intellij: false
packages:
  - "."
  - example/**
command:
  bootstrap:
    hooks:
      post: |
        melos run format
  version:
    workspaceChangelog: true
    branch: main
    message: |
      chore: cut package releases 🎉
scripts:
  postclean: >
    melos exec -c 1 -- "flutter pub get"
  format:
    description: |
      Run `dart format` in all packages.
    run: |
      melos exec -c 1 -- \
        "dart format ."
