name: mwc
description: >
  Melos Workspace Cleaner is a tool designed for cleaning monorepo workspaces
  built on the Melos
version: 0.1.3
homepage: https://github.com/zoocityboy/melos_workspace_cleaner
repository: https://github.com/zoocityboy/melos_workspace_cleaner
issue_tracker: https://github.com/zoocityboy/melos_workspace_cleaner/issues
topics: [melos, dart, monorepo, workspace, cleaner]
screenshots:
  - description: Workspace Cleaner
    path: assets/workspace_cleaner.webp
  - description: Workspace Cleaner icon
    path: assets/workspace_icon.webp

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  cli_launcher: ^0.3.1
  glob: ^2.1.2
  mason_logger: ^0.2.11
  meta: ^1.11.0
  pub_updater: ^0.4.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  melos: ^4.0.0
  mocktail: ^1.0.3
  test: ^1.24.0
platforms:
  linux: null
  macos: null
  windows: null
executables:
  mwc: mwc
