# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "lib/**"
      - "test/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: |
          dart pub global activate melos
        
          melos bootstrap
          melos run ci:init
          
      - name: Format
        run: melos run ci:format

      - name: Analyze
        run: melos run ci:analyze

      - name: Run Tests
        run: melos run ci:test
