name: Health
on:
  pull_request:
    branches: [ main ]
    # types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:
  health:
    permissions:
      contents: read
      pull-requests: write
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@main
    with:
      checks: "version,changelog,license,coverage,breaking,do-not-submit"
      fail_on: "version,changelog,do-not-submit"
      warn_on: "license,coverage,breaking"
      coverage_web: false
      upload_coverage: true
      use-flutter: false
      ignore_license: "**.g.dart"
      ignore_coverage: "**.g.dart"
      ignore_packages: "example/,example/packages/package_a,example/packages/package_b,example/packages/package_c"
      checkout_submodules: false