name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  health:
    permissions:
      contents: read
      pull-requests: write
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@main
    with:
      checks: "version,changelog,license,coverage,breaking,do-not-submit"
      fail_on: "version,changelog,do-not-submit"
      warn_on: "license,coverage,breaking"
      coverage_web: false
      upload_coverage: true
      use-flutter: false
      ignore_license: "**.g.dart"
      ignore_coverage: "**.g.dart"
      ignore_packages: "example/,example/packages/package_a,example/packages/package_b,example/packages/package_c"
      checkout_submodules: false
  summary:
    needs: health
    runs-on: ubuntu-latest
    steps:
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
  publish:
    needs: health
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

          